FROM node:24-alpine

ARG OTEL_ENABLED=false

ENV AUTHENTICATION_HOST=http://localhost:3001
ENV CERTIFICATION_HOST=http://localhost:3002
ENV OTLP_HOST=http://localhost:4318
ENV VITE_OTEL_ENABLED=${OTEL_ENABLED}

WORKDIR /app

COPY *.json .

RUN npm install

COPY . .

RUN npm run build

EXPOSE 5173

CMD ["npm", "run", "preview", "--", "--host", "--port", "5173"]
